### ISSUE TITLE
Tinyissue Logo not displayed

### ISSUE THREAD

**Issue by knusperpixel** [mikelbring/tinyissue#104]
In Windows XP/Google Chrome (Version 25.0.1364.172 m) the Tinyissue Logo is not visible.

I had to update /app/assets/css/app.css and changed line 280 - 285.

Old:

``` CSS
#header .logo{
    width: 87px; height: 23px;
    background: url('../images/layout/tinyissue.png') no-repeat;
    text-indent: -99999999px !important;
    position: absolute; top: 15px; left: 15px;
}
```

New:

``` CSS
#header .logo{
    width: 87px; height: 23px;
    background: url('../images/layout/tinyissue.png') no-repeat;
    text-indent: 100%; /* No need for !important here */
    position: absolute; top: 15px; left: 15px;
    white-space:nowrap; /* Make sure the text does not wrap */
    overflow:hidden; /* Make sure the text is not visible */
}
```
